### ISSUE TITLE
Implement a way to hide the tokens passed to the module

### ISSUE THREAD

**Issue by jviotti** [resin-io-modules/resin-raven#21]
It'd be really cool if we can allow corvus to hide the analytics token even if the user has the final packaged code (e.g. the electron app).

I don't have a clear solution in mind, but something to think about.

**Comment by lurch** [comment]
I think the best you could do would be to store the tokens in the app in an obfuscated fashion, and then have the app only unobfuscate them immediately before it needs to use them (but of course there'd still be nothing stopping a user from applying the same unobfuscation algorithm to reveal the original tokens, if they were really determined).
AFAIK this is a problem common to all desktop-side apps (rather than server-side) that use e.g. OAuth.

**Comment by jviotti** [comment]
Closing stale issues
